name-template: 'v$RESOLVED_VERSION 🌟'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🍣 Enhancement'
    label: 'enhancement'
  - title: '🐝 Bug Fixes'
    label: 'bug'
  - title: '🍰 Documentation'
    label: 'documentation'
  - title: '🖋 Renovate update'
    label: 'renovate'
  - title: '🍺 Refactor a code'
    label: 'refactor'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes

  $CHANGES
